abbr -a blink "./scripts/blink.sh"
abbr -a dim "./scripts/dim.sh"
abbr -a bold "./scripts/embolden.sh"
abbr -a hide "./scripts/hide.sh"
abbr -a invert "./scripts/invert.sh"
abbr -a ital "./scripts/italicize.sh"
abbr -a cread "./scripts/colorread.sh"
abbr -a strike "./scripts/strikethrough.sh"
abbr -a uline "./scripts/underline.sh"

