abbr -a blink "./scripts/stylize.sh blink"
abbr -a dim "./scripts/stylize.sh dim"
abbr -a bold "./scripts/stylize.sh bold"
abbr -a hide "./scripts/stylize.sh hide"
abbr -a invert "./scripts/stylize.sh invert"
abbr -a ital "./scripts/stylize.sh ital"
abbr -a cread "./scripts/colorread.sh"
abbr -a strike "./scripts/stylize.sh strike"
abbr -a uline "./scripts/stylize.sh uline"
